name: hello
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get difference
        run: git diff-tree --name-status -r @{1} master
        
