name: hello
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v1

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3

      - name: Current branch name
        run: |
          git rev-parse --abbrev-ref HEAD
          echo "$GITHUB_REF"

      - name: Print files.json
        if: github.head_ref != 'master'
        run: node ./foo.js

      - name: Print all files
        if: github.head_ref == 'master'
        run: node ./bar.js
